/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'orderId' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'orderId' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };